WITH

SRC AS

(
SELECT 'Account_Details' AS TABLE_NAME,'AccountID' AS COLUMN_NAME,'int' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'NO' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'CustomerID' AS COLUMN_NAME,'int' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'NO' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'AccountType' AS COLUMN_NAME,'VARCHAR' AS DATA_TYPE,20 AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'OpenDate' AS COLUMN_NAME,'DATE' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'HashKey' AS COLUMN_NAME,'VARCHAR' AS DATA_TYPE,64 AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'IsActive' AS COLUMN_NAME,'bit' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'IsDelete' AS COLUMN_NAME,'bit' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'EffectiveStartDate' AS COLUMN_NAME,'datetime' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'EffectiveEndDate' AS COLUMN_NAME,'datetime' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE 

),

TGT AS
 
(

SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,IS_NULLABLE 

FROM INFORMATION_SCHEMA.COLUMNS

WHERE TABLE_NAME='Account_Details'
 
 
)  

SELECT 'SOURCE',COUNT(*) FROM SRC

UNION ALL

SELECT 'TARGET',COUNT(*) FROM TGT

UNION ALL

SELECT 'SOURCE INTERSECT TARGET',COUNT(*) FROM

(

SELECT 'SOURCE - TARGET' AS QRY,SRC.* FROM SRC

INTERSECT

SELECT 'SOURCE - TARGET' AS QRY,TGT.* FROM TGT

)tt

UNION ALL

SELECT 'TARGET INTERSECT SOURCE',COUNT(*) FROM

(

SELECT 'TARGET - SOURCE' AS QRY,TGT.* FROM TGT

INTERSECT

SELECT 'TARGET - SOURCE' AS QRY,SRC.* FROM SRC

)tt1

UNION ALL

SELECT 'SOURCE MINUS TARGET',COUNT(*) FROM

(

SELECT 'SOURCE - TARGET' AS QRY,SRC.* FROM SRC

EXCEPT

SELECT 'SOURCE - TARGET' AS QRY,TGT.* FROM TGT

)tt2

UNION ALL

SELECT 'TARGET MINUS SOURCE',COUNT(*) FROM

(

SELECT 'TARGET - SOURCE' AS QRY,TGT.* FROM TGT

EXCEPT

SELECT 'TARGET - SOURCE' AS QRY,SRC.* FROM SRC

)tt3 

/* SELECT * FROM
(SELECT QRY,TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,IS_NULLABLE FROM
(
SELECT 'SOURCE - TARGET' AS QRY,SRC.* FROM SRC
EXCEPT
SELECT 'SOURCE - TARGET' AS QRY,TGT.* FROM TGT)tt5
UNION ALL
SELECT QRY,TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,IS_NULLABLE FROM
(
SELECT 'TARGET - SOURCE' AS QRY,TGT.* FROM TGT
EXCEPT
SELECT 'TARGET - SOURCE' AS QRY,SRC.* FROM SRC)tt6
)tt7
ORDER BY COLUMN_NAME */

