WITH
SRC AS
(
SELECT 'Account_Details' AS TABLE_NAME,'AccountID' AS COLUMN_NAME,'int' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'NO' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'CustomerID' AS COLUMN_NAME,'int' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'NO' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'AccountType' AS COLUMN_NAME,'VARCHAR' AS DATA_TYPE,20 AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'OpenDate' AS COLUMN_NAME,'DATE' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'HashKey' AS COLUMN_NAME,'VARCHAR' AS DATA_TYPE,64 AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'IsActive' AS COLUMN_NAME,'bit' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'IsDelete' AS COLUMN_NAME,'bit' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'EffectiveStartDate' AS COLUMN_NAME,'datetime' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE UNION
SELECT 'Account_Details' AS TABLE_NAME,'EffectiveEndDate' AS COLUMN_NAME,'datetime' AS DATA_TYPE,NULL AS CHARACTER_MAXIMUM_LENGTH,'YES' AS IS_NULLABLE 

),
TGT AS 
(
    SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,IS_NULLABLE 
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME='Account_Details'
),
RS AS 
(
    SELECT 'SOURCE' AS CNAME,COUNT(*) AS VAL FROM SRC
    UNION ALL
    SELECT 'TARGET',COUNT(*) FROM TGT
    UNION ALL
    SELECT 'SOURCE_INTERSECT_TARGET',COUNT(*) FROM
    (
        SELECT * FROM SRC
        INTERSECT
        SELECT * FROM TGT
    ) tt
    UNION ALL
    SELECT 'TARGET_INTERSECT_SOURCE',COUNT(*) FROM
    (
         SELECT * FROM TGT
        INTERSECT
        SELECT * FROM SRC
    ) tt1

    UNION ALL
    SELECT 'SOURCE_MINUS_TARGET',COUNT(*) FROM
    (
        SELECT * FROM SRC
        EXCEPT
        SELECT * FROM TGT
    ) tt2
    UNION ALL
    SELECT 'TARGET_MINUS_SOURCE',COUNT(*) FROM
    (
        SELECT * FROM TGT
        EXCEPT
        SELECT * FROM SRC
    ) tt3
)

INSERT INTO Automationresults
(
    TABLENAME,
    VALIDATION,
    TEST_RESULTS,
    SOURCECOUNT,
    TARGETCOUNT,
    SOURCE_INTERSECT_TARGET,
    TARGET_INTERSECT_SOURCE,
    SOURCE_MINUS_TARGET,
    TARGET_MINUS_SOURCE
)
SELECT TABLENAME,VALIDATION,TEST_RESULTS,
       SOURCECOUNT,TARGETCOUNT,SOURCE_INTERSECT_TARGET,
       TARGET_INTERSECT_SOURCE,SOURCE_MINUS_TARGET,TARGET_MINUS_SOURCE
FROM (
    SELECT 'Account_Details' AS TABLENAME,
           'DDL_VALIDATION' AS VALIDATION,
           CASE WHEN ((SOURCECOUNT=TARGETCOUNT) 
                  AND (TARGETCOUNT=SOURCE_INTERSECT_TARGET) 
                  AND (SOURCE_INTERSECT_TARGET=TARGET_INTERSECT_SOURCE)
                  AND (SOURCE_MINUS_TARGET=0) 
                  AND (TARGET_MINUS_SOURCE=0)) 
                THEN 'PASS'
                ELSE 'FAIL' END AS TEST_RESULTS,
           SOURCECOUNT,TARGETCOUNT,SOURCE_INTERSECT_TARGET,
           TARGET_INTERSECT_SOURCE,SOURCE_MINUS_TARGET,TARGET_MINUS_SOURCE
    FROM (
        SELECT MAX(CASE WHEN CNAME = 'SOURCE' THEN VAL END) AS SOURCECOUNT,
               MAX(CASE WHEN CNAME = 'TARGET' THEN VAL END) AS TARGETCOUNT,
               MAX(CASE WHEN CNAME = 'SOURCE_INTERSECT_TARGET' THEN VAL END) AS SOURCE_INTERSECT_TARGET,
               MAX(CASE WHEN CNAME = 'TARGET_INTERSECT_SOURCE' THEN VAL END) AS TARGET_INTERSECT_SOURCE,
               MAX(CASE WHEN CNAME = 'SOURCE_MINUS_TARGET' THEN VAL END) AS SOURCE_MINUS_TARGET,
               MAX(CASE WHEN CNAME = 'TARGET_MINUS_SOURCE' THEN VAL END) AS TARGET_MINUS_SOURCE
        FROM RS
    ) X
) Y




/*CReate table Automationresults
(
TABLENAME VARCHAR(50),
VALIDATION VARCHAR(50),
TEST_RESULTS VARCHAR(50),
SOURCECOUNT INT,
TARGETCOUNT INT,
SOURCE_INTERSECT_TARGET INT,
TARGET_INTERSECT_SOURCE INT,
SOURCE_MINUS_TARGET INT,
TARGET_MINUS_SOURCE INT
) */

Select * from Automationresults